# Generated by Django 5.2.15 on 2026-06-20 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('tipo', models.CharField(choices=[('pronta', 'Pronta'), ('sob_medida', 'Sob medida')], default='pronta', max_length=20, verbose_name='tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='catalogo.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'peça',
                'verbose_name_plural': 'peças',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='pecas/', verbose_name='arquivo')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.peca', verbose_name='peça')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
                'ordering': ['-principal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('Único', 'Único')], max_length=20, verbose_name='tamanho')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='cor')),
                ('estoque', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'O estoque não pode ser negativo.')], verbose_name='estoque')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalogo.peca', verbose_name='peça')),
            ],
            options={
                'verbose_name': 'variação',
                'verbose_name_plural': 'variações',
                'ordering': ['tamanho', 'cor'],
                'unique_together': {('peca', 'tamanho', 'cor')},
            },
        ),
    ]
