# Generated by Django 5.2.15 on 2026-06-20 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('contato', models.CharField(max_length=100, verbose_name='contato')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('tamanho_medidas', models.CharField(blank=True, max_length=255, verbose_name='tamanho/medidas')),
                ('prazo_desejado', models.DateField(blank=True, null=True, verbose_name='prazo desejado')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='recebido', max_length=20, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'encomenda',
                'verbose_name_plural': 'encomendas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EncomendaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='encomendas/', verbose_name='arquivo')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.encomenda', verbose_name='encomenda')),
            ],
            options={
                'verbose_name': 'imagem de encomenda',
                'verbose_name_plural': 'imagens de encomenda',
                'ordering': ['id'],
            },
        ),
    ]
