# Generated by Django 5.2.15 on 2026-06-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_encomenda_encomendaimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='destaque',
            field=models.BooleanField(default=False, help_text="Aparece na seção 'Peças em destaque' da Home.", verbose_name='destaque'),
        ),
    ]
