# Generated by Django 5.2.15 on 2026-06-21 21:31
#
# Inclui uma data migration que desduplica `Categoria.nome` ANTES de aplicar a
# restrição de unicidade (a criação do índice único falha se houver repetidos).
# Mesmo padrão usado na 0004 para `Peca.nome`: acrescenta sufixos " (2)",
# " (3)"… aos nomes repetidos, mantendo o primeiro registro (menor id) intacto.

import django.core.validators
from django.db import migrations, models


def desduplicar_nomes_categoria(apps, schema_editor):
    Categoria = apps.get_model("catalogo", "Categoria")
    vistos = {}
    # Ordena por id para manter o primeiro registro de cada nome sem sufixo.
    for categoria in Categoria.objects.order_by("id").iterator():
        base = categoria.nome
        if base not in vistos:
            vistos[base] = 1
            continue
        # Já existe esse nome: gera um sufixo único que ainda não exista.
        contador = vistos[base] + 1
        novo = f"{base} ({contador})"
        while (
            Categoria.objects.filter(nome=novo).exclude(pk=categoria.pk).exists()
            or novo in vistos
        ):
            contador += 1
            novo = f"{base} ({contador})"
        vistos[base] = contador
        vistos[novo] = 1
        categoria.nome = novo
        categoria.save(update_fields=["nome"])


def reverter(apps, schema_editor):
    # Não há como reconstruir os nomes originais com segurança; no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_peca_nome_unico_categoria_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='nome')),
                ('hex', models.CharField(help_text='Cor no formato #RRGGBB (ex.: #B07A56).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='hex')),
            ],
            options={
                'verbose_name': 'cor',
                'verbose_name_plural': 'cores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='variacao',
            name='cor_hex',
            field=models.CharField(blank=True, max_length=7, verbose_name='cor (hex)'),
        ),
        # Desduplica ANTES de criar o índice único em Categoria.nome.
        migrations.RunPython(desduplicar_nomes_categoria, reverter),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Já existe uma categoria com esse nome.'}, max_length=100, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='descricao',
            field=models.TextField(max_length=600, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.TextField(blank=True, max_length=600, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Já existe uma peça com esse nome.'}, max_length=80, unique=True, verbose_name='nome'),
        ),
    ]
