# Generated by Django 5.2.15 on 2026-06-22 02:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_cor_variacao_cor_hex_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(max_length=100, unique=True, verbose_name='ID do evento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'evento de pagamento',
                'verbose_name_plural': 'eventos de pagamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('contato', models.CharField(max_length=100, verbose_name='contato')),
                ('status', models.CharField(choices=[('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='aguardando_pagamento', max_length=30, verbose_name='status')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, verbose_name='ID da preferência (MP)')),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID do pagamento (MP)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'A quantidade deve ser pelo menos 1.')], verbose_name='quantidade')),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='catalogo.variacao', verbose_name='variação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='catalogo.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'ordering': ['id'],
            },
        ),
    ]
