# Generated by Django 5.2.15 on 2026-06-25 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_mensagemwhatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('dono', 'Dono'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20, verbose_name='papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('acesso_financeiro', models.BooleanField(default=False, help_text='Libera a seção Vendas/financeiro para um funcionário.', verbose_name='acesso ao financeiro')),
                ('senha_provisoria', models.BooleanField(default=False, help_text='Quando verdadeiro, força a troca de senha no próximo acesso.', verbose_name='senha provisória')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'ordering': ['usuario__username'],
            },
        ),
    ]
