# Generated by Django 5.2.15 on 2026-06-25 07:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_cliente_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto'),
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('tipo_aplicacao', models.CharField(choices=[('cupom', 'Cupom'), ('automatica', 'Automática')], max_length=20, verbose_name='tipo de aplicação')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('tipo_desconto', models.CharField(choices=[('percentual', 'Percentual (%)'), ('valor', 'Valor (R$)')], max_length=20, verbose_name='tipo de desconto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'O valor do desconto deve ser maior que zero.')], verbose_name='valor')),
                ('escopo', models.CharField(choices=[('tudo', 'Tudo'), ('peca', 'Peça'), ('categoria', 'Categoria')], default='tudo', max_length=20, verbose_name='escopo')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('limite_uso', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de usos')),
                ('usos', models.PositiveIntegerField(default=0, verbose_name='usos')),
                ('acumulavel', models.BooleanField(default=False, help_text='Se o cupom soma com a promoção automática; senão, vale o maior desconto.', verbose_name='acumulável')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes', to='catalogo.categoria', verbose_name='categoria')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes', to='catalogo.peca', verbose_name='peça')),
            ],
            options={
                'verbose_name': 'promoção',
                'verbose_name_plural': 'promoções',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='catalogo.promocao', verbose_name='cupom'),
        ),
        migrations.AddConstraint(
            model_name='promocao',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_aplicacao', 'cupom')), fields=('codigo',), name='codigo_unico_por_cupom'),
        ),
    ]
