# Generated by Django 5.2.15 on 2026-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_pedido_desconto_promocao_pedido_cupom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='peca',
        ),
        migrations.AddField(
            model_name='promocao',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='promocoes', to='catalogo.categoria', verbose_name='categorias'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='pecas',
            field=models.ManyToManyField(blank=True, related_name='promocoes', to='catalogo.peca', verbose_name='peças'),
        ),
    ]
