# Generated by Django 5.2.15 on 2026-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_remove_promocao_categoria_remove_promocao_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=60, verbose_name='código de rastreio'),
        ),
    ]
