# Generated by Django 5.2.15 on 2026-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_pedido_codigo_rastreio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_revisao',
            field=models.CharField(blank=True, choices=[('divergencia_valor', 'Valor pago diferente do total'), ('pago_apos_expiracao', 'Pago após a expiração'), ('sem_estoque_apos_pago', 'Sem estoque na confirmação')], max_length=30, verbose_name='motivo da revisão'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('em_revisao', 'Em revisão')], default='aguardando_pagamento', max_length=30, verbose_name='status'),
        ),
    ]
